### ISSUE TITLE
Пустой запрос на форму регистрации выкидывает предупреждения

### ISSUE THREAD

**Issue by caseycs** [htmlacademy-php/48724-yeticave#18]
``
~> curl -X POST http://0.0.0.0:3000/sign-up.php
<br />
<b>Notice</b>:  Undefined index: name in <b>/Users/ilia.kondrashov/htmlacademy/48724-yeticave/sign-up.php</b> on line <b>31</b><br />
<br />
<b>Notice</b>:  Undefined index: email in <b>/Users/ilia.kondrashov/htmlacademy/48724-yeticave/sign-up.php</b> on line <b>32</b><br />
<br />
<b>Notice</b>:  Undefined index: message in <b>/Users/ilia.kondrashov/htmlacademy/48724-yeticave/sign-up.php</b> on line <b>33</b><br />
<br />
<b>Notice</b>:  Undefined index: password in <b>/Users/ilia.kondrashov/htmlacademy/48724-yeticave/sign-up.php</b> on line <b>34</b><br />
<br />
<b>Notice</b>:  Undefined index: password in <b>/Users/ilia.kondrashov/htmlacademy/48724-yeticave/sign-up.php</b> on line <b>91</b><br />
```

**Comment by plushevy** [comment]
поправил
