### ISSUE TITLE
При регистрации с email которого нет в базе вижу ошибку "email уже зарегистрирован"

### ISSUE THREAD

**Issue by caseycs** [htmlacademy-php/48724-yeticave#19]
Повторяется если есть ошибка валидации в любом другом поле

https://www.dropbox.com/s/znkilydf24o6hb5/Screenshot%202019-03-02%2014.13.46.png?dl=0

**Comment by plushevy** [comment]
поправил и перенес проверку на сущ email в проверки полей наверх
