### ISSUE TITLE
Пустой POST запрос к авторизации выбрасывает предупреждения

### ISSUE THREAD

**Issue by caseycs** [htmlacademy-php/48724-yeticave#20]
```
~> curl -X POST http://0.0.0.0:3000/login.php
<br />
<b>Notice</b>:  Undefined index: email in <b>/Users/ilia.kondrashov/htmlacademy/48724-yeticave/login.php</b> on line <b>14</b><br />
<br />
<b>Notice</b>:  Undefined index: password in <b>/Users/ilia.kondrashov/htmlacademy/48724-yeticave/login.php</b> on line <b>15</b><br />
<!DOCTYPE html>
<html lang="ru">
<head>
```

Мы разбирали пример как раз как можно упростить проверку на ошибки, я даже скидывал тебе ссылку на описание `??` - но ты сделал чуть иначе чем в моем примере. Надо разобраться в чем проблема.

**Comment by plushevy** [comment]
да я все так и сделал

**Comment by plushevy** [comment]
не работает 

 $name = cleanVal($_POST['name']) ?? '';
 $email = cleanVal($_POST['email']) ?? '';

**Comment by caseycs** [comment]
Ну почему же, как написано - так и работает. 

Посмотри еще раз про два вопросительных знака тут:  http://php.net/manual/en/migration70.new-features.php

Какое значение уходит в `cleanVal` сейчас?

**Comment by caseycs** [comment]
И еще наводящий вопрос - а какое значение приходит в переменные (name/email)? Что происходит сперва - вызов функции или null coalescing?

**Comment by plushevy** [comment]
Это-то я как раз и не очень понимаю.  Из документации не понятно, как это будет с ф-цией, тут просто сокращение от isset и все: 

// Fetches the value of $_GET['user'] and returns 'nobody'
// if it does not exist.
$username = $_GET['user'] ?? 'nobody';
// This is equivalent to:
$username = isset($_GET['user']) ? $_GET['user'] : 'nobody';

**Comment by plushevy** [comment]
Все делал по подобию https://github.com/plushevy/48724-yeticave/pull/1/files?utf8=✓&diff=split&w=1

**Comment by caseycs** [comment]
Верно все пишешь, и примеры приводишь верные.
А теперь посмотри на свой код, на примеры в своем прошлом комментарии, на PR ссылку на который ты привел и на свой код. 

Видишь разницу?

**Comment by caseycs** [comment]
Уже совсем не наводящий пример:

```
$b = someFunction($a) ?? null;
$b = someFunction($a ?? null);
```

В чем отличие?

**Comment by plushevy** [comment]
да в ф-ции

**Comment by plushevy** [comment]
и как мне кажется $b = isset(someFunction($a)) ? someFunction($a) :  null;

**Comment by plushevy** [comment]
и поэтому и не работает

**Comment by caseycs** [comment]
Это в каком случае?

**Comment by plushevy** [comment]
мне кажется что это одно и тоже 
$b = someFunction($a ?? null);
 $b = isset(someFunction($a)) ? someFunction($a) : null;

**Comment by caseycs** [comment]
Нет, это не так

```
$b = someFunction($a) ?? null;
1. $tmp = someFunction($a)
2. $b = $tmp ?? null

$b = someFunction($a ?? null);
1. $tmp = $a ?? null
2. $b = someFunction($tmp)
```

**Comment by caseycs** [comment]
Два раза функция не вызывается - совершенно точно.

**Comment by caseycs** [comment]
Т.е. 

```
$b = someFunction($a ?? null);
$b =someFunction(isset($a) ? $a : null);
```

**Comment by plushevy** [comment]
тогда должно работать, но не работает

**Comment by caseycs** [comment]
Давай разберем еще раз.

```
cleanVal($_POST['name']) ?? '';
```

все равно что 

```
$tmp = cleanVal($_POST['name']);
isset($tmp) ? $tmp : '';
```

На первой строчке все еще есть обращение к несуществующей переменной.
Т.е. работает как и должно, и ошибка ожидаемая.

**Comment by caseycs** [comment]
Как сделать так, чтобы isset проверка была ДО того, как вызовется функция?

**Comment by plushevy** [comment]
$b =$a ?? null;
$b = someFunction($b)

**Comment by caseycs** [comment]
Верно. 
А теперь смотри:

```
$b = 5
$b = someFunction($b)
```

Все равно что 

```
$b = someFunction(5)
```

Верно?

**Comment by plushevy** [comment]
верно

**Comment by caseycs** [comment]
Вот. А теперь посмотри на то, с чего мы начинали - видишь теперь разницу?

**Comment by plushevy** [comment]
$name = cleanVal($_POST['name'] ?? ' ');

**Comment by caseycs** [comment]
Да, в моем примере было именно так. Понимаешь в чем отличие?

**Comment by plushevy** [comment]
да я этого просто не увидел

**Comment by plushevy** [comment]
и решил, что раз ты написал так как я думал - то оно и должно работать, а проверяю - ошибка

**Comment by plushevy** [comment]
а беглым взглядом не заметил где скобка

**Comment by caseycs** [comment]
Ну то мы и учимся. Видишь, заодно вскрылось что порядок выполнения вызывает вопросы, вот и прояснили (надеюсь).

Т.е. важно понимать, что выполнение происходит всего "из глубины" наружу

**Comment by caseycs** [comment]
Я потому и не стал поправлять "типа надо так" ибо заподозрил что нет до конца понимания. Прояснилось сейчас?

**Comment by caseycs** [comment]
Вот тут вот я прямо описал: https://github.com/htmlacademy-php/48724-yeticave/issues/20#issuecomment-468969287

**Comment by plushevy** [comment]
да на самом деле мог и сказать)) понимание есть, но невнимательность тоже есть ))

**Comment by plushevy** [comment]
но теперь точно запомнится, спасибо

**Comment by plushevy** [comment]
поправил
