### ISSUE TITLE
Добавление ставки по умолчанию не работает

### ISSUE THREAD

**Issue by caseycs** [htmlacademy-php/48724-yeticave#21]
Захожу на страницу лота, вижу минимальную ставку, это же значение предзаполнено в форму.  Нажимаю "сделать" вижу ошибку `Введите число больше мин. ставки`

**Comment by caseycs** [comment]
Аааа, это потому что ты не в input value вставляешь минимальную ставку, а в placeholder. Предлагаю поправить, неочевидно ни разу.

**Comment by plushevy** [comment]
поправил
