### ISSUE TITLE
В mysql_helper.php и functions.php иногда неверно описаны параметры функций

### ISSUE THREAD

**Issue by caseycs** [htmlacademy-php/48724-yeticave#22]
* нет такого типа `number`
* `@param type $variable`

**Comment by plushevy** [comment]
а если тип может быть любой, как у debug

**Comment by plushevy** [comment]
поправил

**Comment by caseycs** [comment]
Поправил, а где - можешь сделать пулл-реквест с правками? Лучше - по одному на тикет, но не критично.

**Comment by plushevy** [comment]
аа ок. я просто сначала тут написал а коммит еще не сделал

**Comment by plushevy** [comment]
ресурсу соединения и mysqli statement указал тип - resource
